### ISSUE TITLE
advise using a Linux VM on Windows?

### ISSUE THREAD

**Issue by afeld** [onemonth/install_rails#10]
While RailsInstaller hopefully mitigates a lot of the early pain of installation, it's inevitable that people will run into problems of gems that aren't Windows-compatible.  It's just a sub-par experience for working in Rails.  Thoughts about advising them to set up Ubuntu in Virtualbox instead?

**Comment by rodrigoargumedo** [comment]
@afeld You can try [c9](http://c9.io) for free to do the heavy-lifting and it comes with Linux VM with Ubuntu 14.04 and full root access.
